### ISSUE TITLE
Neo4j 3.0 Parentheses sintax error 

### ISSUE THREAD

**Issue by tobiadalsecco** [brikteknologier/seraph-model#108]
Running the beer example with Neo4j 3.0.2:

var beer = model(db, "Beer");
var hop = model(db, "Hop");
 
beer.compose(hop, 'hops', 'contains_hop');
 
var pliny = {
  name: 'Pliny the Elder',
  brewery: 'Russian River',
  hops: [
    { name: 'Columbus', aa: '13' },
    { name: 'Simcoe', aa: '12' },
    { name: 'Centennial', aa: '8' }
  ]
};

beer.save(pliny, function(err, saved) {
  console.log(err, saved);
});

I got the following error:

{ code: 'Neo.ClientError.Statement.SyntaxError',
  message: 'Parentheses are required to identify nodes in patterns, i.e. (Beer0) (line 1, column 71 (offset: 70))\n"   CREATE (Beer0:Beer),(Hop0:Hop),(Hop1:Hop),(Hop2:Hop) CREATE UNIQUE Beer0-[__rel_Hop0:contains_hop]->Hop0,Beer0-[__rel_Hop1:contains_hop]->Hop1,Beer0-[__rel_Hop2:contains_hop]->Hop2 SET Beer0={Beer0},__rel_Hop0={__rel_Hop0},Hop0={Hop0},__rel_Hop1={__rel_Hop1},Hop1={Hop1},__rel_Hop2={__rel_Hop2},Hop2={Hop2} WITH Beer0,Hop0,__rel_Hop0,Hop1,__rel_Hop1,Hop2,__rel_Hop2 OPTIONAL MATCH Beer0-[rel:`contains_hop`]->target WHERE not (target IN [Beer0,Hop0,Hop1,Hop2]) DELETE rel RETURN Beer0,Hop0,__rel_Hop0,Hop1,__rel_Hop1,Hop2,__rel_Hop2"\n

**Comment by shanmarkus** [comment]
i still experience this problem

**Comment by shanmarkus** [comment]
Unhandled rejection Parentheses are required to identify nodes in patterns, i.e. (pomonaUser0) (line 1, column 71 (offset: 70))

"   CREATE (pomonaUser0:pomonaUser),(merchant0:merchant) CREATE UNIQUE pomonaUser0-[__rel_merchant0:go_to]->merchant0 SET pomonaUser0={pomonaUser0},__rel_merchant0={__rel_merchant0},merchant0={merchant0} WITH pomonaUser0,merchant0,__rel_merchant0 OPTIONAL MATCH pomonaUser0-[rel:`go_to`|`check_out`]->target WHERE not (target IN [pomonaUser0,merchant0]) DELETE rel RETURN pomonaUser0,merchant0,__rel_merchant0"

**Comment by bornytm** [comment]
Also running into this issue.

```
{ code: 'Neo.ClientError.Statement.SyntaxError',
  message: 'Parentheses are required to identify nodes in patterns, i.e. (Beer0) (line 1, column 71 (offset: 70))\n"   CREATE (Beer0:Beer),(Hop0:Hop),(Hop1:Hop),(Hop2:Hop) CREATE UNIQUE Beer0-[__rel_Hop0:contains_hop]->Hop0,Beer0-[__rel_Hop1:contains_hop]->Hop1,Beer0-[__rel_Hop2:contains_hop]->Hop2 SET Beer0={Beer0},__rel_Hop0={__rel_Hop0},Hop0={Hop0},__rel_Hop1={__rel_Hop1},Hop1={Hop1},__rel_Hop2={__rel_Hop2},Hop2={Hop2} WITH Beer0,Hop0,__rel_Hop0,Hop1,__rel_Hop1,Hop2,__rel_Hop2 OPTIONAL MATCH Beer0-[rel:`contains_hop`]->target WHERE not (target IN [Beer0,Hop0,Hop1,Hop2]) DELETE rel RETURN Beer0,Hop0,__rel_Hop0,Hop1,__rel_Hop1,Hop2,__rel_Hop2"\n       
```

**Comment by jonpacker** [comment]
This should be fixed now, try updating to 0.8.3.

**Comment by shanmarkus** [comment]
thank you @jonpacker

**Comment by tobiadalsecco** [comment]
It worked, thanks @jonpacker !
