### ISSUE TITLE
Joining relationship properties with nested model

### ISSUE THREAD

**Issue by optimista** [brikteknologier/seraph-model#64]
Hello there, love the package, especially model composition is great feature. I would like to ask if it is possible to include relationship properties in nested model properties.

Let's say  we have node bar and it has many beers, multiple bars might serve the same beer, but the price might be different in different bars so it comes logical to put price property into a relationship between beer and bar, but once you read the composed model of bar, you have already chosen bar, which includes many beers and including the price property from the relationship in nested beer model would help a lot.

Thank you! Viktor F.

```JSON
{
  "id": 1
  "beers": [
    {
      "id": 2,
      "brand": "Great Beer",
      "price": "0.99" //Relationship property
    },
    {
      "id": 3,
      "brand": "Even Greater Beer",
      "price": "1.19" //Relationship property
    }
  ]
}
```

**Comment by IcanDivideBy0** [comment]
Is there anyone working on this ? I'd like to try implement this feature.

**Comment by jonpacker** [comment]
Go for it!

**Comment by highfivedenis** [comment]
@IcanDivideBy0 :+1:

**Comment by IcanDivideBy0** [comment]
I think the object model proposed by @optimista might be a bit confusing about what's in the related model and what's in the relation. Also there's no good place to store the relation ID, which might be useful for future features (such as update a relation properties, ...).

What do you think about the following structure ?
```js
{
  id: 1,
  beers: [{
    id: 2,
    brand: "Great Beer",
    _rel: { price: "0.99", ... } // relationship properties
  }, {
    id: 3,
    brand: "Even Greater Beer",
    _rel: { price: "1.19", ... } // relationship properties
  }]
}
```
Of course the `_rel` property name is totally arbitrary, but gives a good overview of what it represents.
It might be closer to what ORM generally offers and also avoid property collision ever an object and a relation pointing to it.
