### ISSUE TITLE
Expose Model class

### ISSUE THREAD

**Issue by vinerz** [brikteknologier/seraph-model#95]
Hello! Thank you for this great tool. I am having a great time discovering neo4j and seraph.

However, I miss the exposal of the Model object.

I want to create some new methods that will apply to every new model created by the factory, but I can't find a way to do that without creating a fork of the module only to change the way it exports the model factory.

**Comment by jonpacker** [comment]
Good idea! I've exposed it as `model.modelPrototype`. So you can change it by adding stuff like:

```javascript
var model = require('seraph-model');
model.modelPrototype.myNewFunction = function() {}
```

**Comment by vinerz** [comment]
Whoa, that was quick! Thank you Jon, you rock!
